//! The vault's repo split, ported from scripts/exo_repos.py: who owns each path (`owner`, `plan`), the paper list
//! (`manifest`) and what an on-demand repo checks out (`ALWAYS`). Only the parts that need no git and no disk; the
//! commands that run git are in the desktop app's vaultcli.rs and vault.rs. Output is the Python's, byte for byte.

use serde::Serialize;
use serde_json::Value;
use std::collections::{BTreeMap, BTreeSet, HashMap};

/// What an on-demand repo (Papers) always checks out; the PDFs stay on GitHub until opened.
/// The Obsidian plugin keeps a copy (PAPERS_ALWAYS in engine.ts): change both together.
pub const ALWAYS: [&str; 8] = ["/_manifest.json", "*.md", "*.jpg", "*.jpeg", "*.png", "*.svg", "*.enl", "*.canvas"];

/// Where the paper list lives and what it says about itself.
pub const PAPERS: &str = "Papers";
const ABOUT: &str = "Generated by scripts/exo_repos.py manifest. Lists every PDF so the Papers tab needs no git object to show it.";

// ---------------------------------------------------------------- owners

fn s<'a>(v: &'a Value, k: &str) -> &'a str { v.get(k).and_then(Value::as_str).unwrap_or("") }

fn routes(cfg: &Value) -> &[Value] { cfg["routes"].as_array().map_or(&[], Vec::as_slice) }

/// The longest route whose prefix is the path itself or a folder (ending in /) holding it; the first of equals wins,
/// as Python's max() does.
pub fn route<'a>(cfg: &'a Value, rel: &str) -> Option<&'a Value> {
    routes(cfg).iter()
        .filter(|r| { let p = s(r, "prefix"); rel == p || (p.ends_with('/') && rel.starts_with(p)) })
        .fold(None, |best: Option<&Value>, r| match best { Some(b) if s(b, "prefix").len() >= s(r, "prefix").len() => Some(b), _ => Some(r) })
}

/// Primary logs (`_*.md`) and registered system docs go to the book; otherwise the longest matching route.
pub fn owner(cfg: &Value, rel: &str, system_doc: bool) -> Option<String> {
    let base = rel.rsplit('/').next().unwrap_or(rel);
    if (base.starts_with('_') && base.ends_with(".md")) || system_doc { return Some(s(cfg, "book").into()) }
    route(cfg, rel).map(|r| s(r, "repo").into())
}

/// Where a file lands in the split vault: its own path, unless its route relocates it ("to").
pub fn placed(cfg: &Value, rel: &str) -> String {
    match route(cfg, rel) {
        Some(r) if !s(r, "to").is_empty() => format!("{}{}", s(r, "to"), &rel[s(r, "prefix").len()..]),
        _ => rel.into(),
    }
}

/// {repo: top-level folder} for every restricted repo; Err with the Python's exit message if a repo spans two.
pub fn folders(cfg: &Value) -> Result<BTreeMap<String, String>, String> {
    let (mut out, mut bad) = (BTreeMap::new(), BTreeSet::new());
    for r in routes(cfg) {
        if s(r, "repo") == s(cfg, "book") { continue }
        let to = if s(r, "to").is_empty() { s(r, "prefix") } else { s(r, "to") };
        let f = to.split('/').next().unwrap_or("").to_string();
        if *out.entry(s(r, "repo").to_string()).or_insert_with(|| f.clone()) != f { bad.insert(s(r, "repo").to_string()); }
    }
    if bad.is_empty() { return Ok(out) }
    let list: Vec<String> = bad.iter().map(|b| format!("'{b}'")).collect();
    Err(format!("repos spanning two folders: [{}] (give the extra route a \"to\")", list.join(", ")))
}

/// The `plan` report for these tracked files: (stdout, exit code). `system_doc` answers is_system_doc().
pub fn plan(cfg: &Value, tracked: &[String], system_doc: &dyn Fn(&str) -> bool) -> Result<(String, i32), String> {
    let homes = folders(cfg)?;
    let own = |rel: &str| owner(cfg, rel, system_doc(rel));
    let (mut count, mut orphans) = (BTreeMap::<String, usize>::new(), vec![]);
    for rel in tracked.iter().filter(|r| *r != ".gitmodules") {
        match own(rel) { Some(o) => *count.entry(o).or_default() += 1, None => orphans.push(rel.as_str()) }
    }
    let mut out = String::new();
    for (repo, n) in &count {
        out += &format!("{n:6}  {repo}  ->  {}\n", homes.get(repo).map_or("(root)", String::as_str));
    }
    for r in routes(cfg).iter().filter(|r| !s(r, "to").is_empty()) {
        out += &format!("moved   {}  ->  {}\n", s(r, "prefix"), s(r, "to"));
    }
    for n in cfg["nested"].as_array().map_or(&[][..], Vec::as_slice) {
        let p = s(n, "path");
        out += &format!("nested  {p}  in {}\n", own(&format!("{p}/")).as_deref().unwrap_or("None"));
    }
    if !orphans.is_empty() {
        out += &format!("\n{} files have no owner:\n{}\n", orphans.len(), orphans.iter().map(|o| format!("  {o}")).collect::<Vec<_>>().join("\n"));
    }
    Ok((out, (!orphans.is_empty()) as i32))
}

// ---------------------------------------------------------------- manifest

/// bytes.decode("utf-8", errors="ignore"): invalid sequences dropped, as Python drops them (maximal subparts).
pub fn utf8_ignore(mut b: &[u8]) -> String {
    let mut out = String::new();
    loop {
        match std::str::from_utf8(b) {
            Ok(t) => { out += t; return out }
            Err(e) => {
                out += std::str::from_utf8(&b[..e.valid_up_to()]).unwrap();
                b = &b[e.valid_up_to() + e.error_len().unwrap_or(b.len() - e.valid_up_to())..];
            }
        }
    }
}

/// re.findall(r"!?\[\[([^\]|#]+\.pdf)", text, re.I): after `[[`, the longest run of characters other than ] | #
/// that ends in .pdf (any case), at least one character before the dot.
pub fn pdf_links(text: &str) -> Vec<&str> {
    let b = text.as_bytes();
    let (mut out, mut i) = (vec![], 0);
    while i + 1 < b.len() {
        if &b[i..i + 2] != b"[[" { i += 1; continue }
        let start = i + 2;
        let run = b[start..].iter().position(|c| b"]|#".contains(c)).map_or(b.len(), |n| start + n);
        match (start + 1..=run.saturating_sub(4)).rev().find(|&j| b[j..j + 4].eq_ignore_ascii_case(b".pdf")) {
            Some(j) => { out.push(&text[start..j + 4]); i = j + 4 }
            None => i += 1,
        }
    }
    out
}

#[derive(Serialize)]
struct Pdf { path: String, bytes: u64, sha: String, linked_from: Vec<String> }

#[derive(Serialize)]
struct Manifest { about: &'static str, pdfs: Vec<Pdf> }

/// Papers/_manifest.json and the line the Python prints. `ls_files` is `git ls-files -s` of the vault (gitlinks are
/// skipped); `size` is the size of a path that is a file on disk; `read` a note's bytes. `windows` makes basename
/// split on \ too, as ntpath does.
pub fn manifest(ls_files: &str, size: &dyn Fn(&str) -> Option<u64>, read: &dyn Fn(&str) -> Option<Vec<u8>>, windows: bool) -> (String, String) {
    let mut files: Vec<&str> = vec![];
    let mut shas = HashMap::new();
    for l in crate::vault_ship::py_splitlines(ls_files) {
        let Some((head, path)) = l.split_once('\t') else { continue };
        shas.insert(path, head.split_whitespace().nth(1).unwrap_or(""));
        if !l.starts_with("160000") { files.push(path) }
    }
    let basename = |p: &str| -> String { if windows { p.rsplit(['/', '\\']).next() } else { p.rsplit('/').next() }.unwrap_or(p).to_string() };
    let prefix = format!("{PAPERS}/");
    let mut pdfs: Vec<&str> = files.iter().copied()
        .filter(|f| f.starts_with(&prefix) && f.to_lowercase().ends_with(".pdf") && size(f).is_some()).collect();
    let mut by_name: HashMap<String, Vec<&str>> = HashMap::new();
    for f in &pdfs { by_name.entry(basename(f)).or_default().push(f) }
    let mut links: HashMap<&str, BTreeSet<String>> = HashMap::new();
    for f in files.iter().filter(|f| f.ends_with(".md")) {
        let Some(bytes) = read(f) else { continue };
        let text = crate::vault_ship::py_text(&utf8_ignore(&bytes));
        for m in pdf_links(&text) {
            for target in by_name.get(&basename(crate::vault_ship::py_strip(m))).into_iter().flatten() {
                links.entry(target).or_default().insert(f.to_string());
            }
        }
    }
    pdfs.sort();
    let out: Vec<Pdf> = pdfs.iter().map(|f| Pdf {
        path: f[prefix.len()..].into(), bytes: size(f).unwrap_or(0), sha: shas.get(f).unwrap_or(&"").to_string(),
        linked_from: links.get(f).map(|l| l.iter().cloned().collect()).unwrap_or_default(),
    }).collect();
    let total: u64 = out.iter().map(|p| p.bytes).sum();
    let line = format!("{} PDFs, {:.0} MB, {} linked from notes", out.len(), total as f64 / 1e6, out.iter().filter(|p| !p.linked_from.is_empty()).count());
    // json.dump(..., ensure_ascii=False, indent=1) and a newline
    let mut buf = vec![];
    let mut ser = serde_json::Serializer::with_formatter(&mut buf, serde_json::ser::PrettyFormatter::with_indent(b" "));
    Manifest { about: ABOUT, pdfs: out }.serialize(&mut ser).unwrap();
    (String::from_utf8(buf).unwrap() + "\n", line)
}

// ---------------------------------------------------------------- download results

/// How one submodule fared in a download or update. `Later` and `Kept` come from the phone only (desktop/src/phonegit.rs).
#[derive(Clone, Copy, PartialEq, Debug)]
pub enum Got {
    Ok, Lazy, Skipped, Conflict,
    /// an on-demand folder (the papers) the phone does not download in this version
    Later,
    /// the person changed files there that the team's version also changes: left as it was, not updated
    Kept,
}

/// One line per submodule, as scripts/exo_repos.py prints them.
pub fn row(path: &str, got: Got) -> String {
    match got {
        Got::Ok => format!("ok      {path}"),
        Got::Lazy => format!("ok      {path}  (on demand: PDFs not downloaded)"),
        Got::Skipped => format!("skipped {path}  (no access or unreachable)"),
        Got::Conflict => format!("CONFLICT {path}  (your changes there and the team's do not fit together: finish the merge in that folder)"),
        Got::Later => format!("later   {path}  (large files: not downloaded on a phone yet)"),
        Got::Kept => format!("kept    {path}  (your changes there are kept; that folder was not updated)"),
    }
}

/// The sentence a download or update ends with.
pub fn summary(what: &str, rows: &[(String, Got)]) -> String {
    let with = |g: Got| rows.iter().filter(|r| r.1 == g).map(|r| r.0.as_str()).collect::<Vec<_>>();
    let ok = rows.iter().filter(|r| matches!(r.1, Got::Ok | Got::Lazy)).count();
    let (skipped, clash, later, kept) = (with(Got::Skipped), with(Got::Conflict), with(Got::Later), with(Got::Kept));
    if !clash.is_empty() {
        return format!("{what}, but your changes in {} do not fit with the team's: open that folder and finish the merge there (git status shows the files)", clash.join(", "));
    }
    let mut s = match (ok, skipped.len()) {
        (0, 0) => what.to_string(),
        (n, 0) => format!("{what} with {n} folders"),
        (n, m) => format!("{what} with {n} folders; {m} you cannot open stay empty ({})", skipped.join(", ")),
    };
    if !kept.is_empty() { s += &format!(". Not updated, because you changed files there: {}", kept.join(", ")) }
    if !later.is_empty() { s += &format!(". Left for later (large files, not downloaded on a phone): {}", later.join(", ")) }
    s
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    /// The selftest's rules.
    fn cfg() -> Value {
        json!({"org": "T", "book": "exo-book", "on_demand": ["exo-papers"], "nested": [], "routes": [
            {"prefix": "System/", "repo": "exo-book"}, {"prefix": "main.md", "repo": "exo-book"}, {"prefix": "Papers/", "repo": "exo-papers"},
            {"prefix": "L3/", "repo": "exo-l3"}, {"prefix": "PM/", "repo": "exo-mgmt"},
            {"prefix": "Secrets/", "repo": "exo-secrets"}, {"prefix": ".token/", "repo": "exo-secrets", "to": "Secrets/.token/"}]})
    }

    #[test]
    fn owners_and_places() {
        let c = cfg();
        assert_eq!(owner(&c, "L3/sub/b.md", false).as_deref(), Some("exo-l3"));
        assert_eq!(owner(&c, "L3/_Log.md", false).as_deref(), Some("exo-book"), "a primary log goes to the book");
        assert_eq!(owner(&c, "L3/guide.md", true).as_deref(), Some("exo-book"), "so does a registered system doc");
        assert_eq!(owner(&c, "main.mdx", false), None, "a file prefix matches only itself");
        assert_eq!(owner(&c, "Other/x.md", false), None);
        assert_eq!(placed(&c, ".token/t.json"), "Secrets/.token/t.json");
        assert_eq!(placed(&c, "L3/a.md"), "L3/a.md");
        let homes = folders(&c).unwrap();
        assert_eq!(homes["exo-secrets"], "Secrets");
        assert!(!homes.contains_key("exo-book"));
        let mut two = c.clone();
        two["routes"].as_array_mut().unwrap().push(json!({"prefix": "Other/", "repo": "exo-l3"}));
        assert_eq!(folders(&two).unwrap_err(), "repos spanning two folders: ['exo-l3'] (give the extra route a \"to\")");
    }

    #[test]
    fn equal_prefixes_keep_the_first_route() {
        let c = json!({"book": "b", "routes": [{"prefix": "A/", "repo": "one"}, {"prefix": "A/", "repo": "two"}]});
        assert_eq!(owner(&c, "A/x", false).as_deref(), Some("one"));
    }

    #[test]
    fn plan_counts_and_orphans() {
        let files: Vec<String> = ["main.md", "System/_Log.md", "L3/a.md", ".gitmodules", "Loose.md"].map(String::from).to_vec();
        let (out, code) = plan(&cfg(), &files, &|_| false).unwrap();
        assert_eq!(out, "     2  exo-book  ->  (root)\n     1  exo-l3  ->  L3\nmoved   .token/  ->  Secrets/.token/\n\n1 files have no owner:\n  Loose.md\n");
        assert_eq!(code, 1);
    }

    #[test]
    fn links_follow_the_python_pattern() {
        assert_eq!(pdf_links("see ![[Big_2024.pdf]] and [[a/B.PDF|x]] [[#c.pdf]] [[.pdf]] [[x.pdf.pdf#p]]"), ["Big_2024.pdf", "a/B.PDF", "x.pdf.pdf"]);
        assert_eq!(pdf_links("[[[a.pdf [[b.pdf]]"), ["[a.pdf [[b.pdf"], "greedy, and [ may be part of the name");
        assert_eq!(pdf_links("[[a\nb.pdf]] [[no"), ["a\nb.pdf"]);
        assert_eq!(utf8_ignore(b"a\xffb\xe4\xb8c\xe4\xb8\xad"), "abc中");
    }

    #[test]
    fn manifest_matches_the_selftest() {
        let ls = "100644 aaa 0\tPapers/Sim/Big_2024.pdf\n100644 bbb 0\tPapers/Sim/Other_2024.pdf\n100644 ccc 0\tSystem/note.md\n\
                  160000 ddd 0\tL3\n100644 eee 0\tPapers/gone.pdf\n";
        let size = |p: &str| (p != "Papers/gone.pdf").then_some(if p.ends_with(".pdf") { 300000 } else { 1 });
        let read = |p: &str| (p == "System/note.md").then(|| b"see ![[Big_2024.pdf]]".to_vec());
        let (json, line) = manifest(ls, &size, &read, false);
        assert_eq!(line, "2 PDFs, 1 MB, 1 linked from notes");
        assert_eq!(json, format!("{{\n \"about\": \"{ABOUT}\",\n \"pdfs\": [\n  {{\n   \"path\": \"Sim/Big_2024.pdf\",\n   \"bytes\": 300000,\n   \"sha\": \"aaa\",\n   \"linked_from\": [\n    \"System/note.md\"\n   ]\n  }},\n  {{\n   \"path\": \"Sim/Other_2024.pdf\",\n   \"bytes\": 300000,\n   \"sha\": \"bbb\",\n   \"linked_from\": []\n  }}\n ]\n}}\n"));
        let (empty, line) = manifest("", &size, &read, false);
        assert_eq!((empty.as_str(), line.as_str()), (&*format!("{{\n \"about\": \"{ABOUT}\",\n \"pdfs\": []\n}}\n"), "0 PDFs, 0 MB, 0 linked from notes"));
    }
}
